version: '3'
services:
  scrapper:
    image: darklotus/dundaa:dev
    build:
      context: .
    command: [ "python", "EventScrapper/ev_loop.py" ]
    volumes:
      - ./:/app/src
    environment:
      AZURE_STORAGE_CONNECTION_STRING : ""
