---

- name: Ensure .ssh directory exists.
  file: path="/home/{{ app_user }}/.ssh/id_rsa" state=directory mode=0700 owner={{ app_user}} group={{ app_user}}

- name: Upload the private key used for Github cloning
  copy: src=ssh.key.j2 dest="/home/{{ app_user }}/.ssh/id_rsa"

- name: Correct SSH deploy key permissions
  file: dest="/home/{{ app_user }}/.ssh/id_rsa" mode=0600