app_name: event-scrapper

app_environment: "prod"

app_user: engineering

app_requirements: "{{ app_directory }}/config/requirements/prod.txt"

app_directory: "/opt/apps/{{ app_name }}"

app_run_directory: "{{ app_directory }}/bin"


app_repository: git@github.com:Piusdan/Dundaa.EventScrapper.git

app_version: master

app_repository_key_file: /home/{{ app_user }}/.ssh/id_rsa

flaskapp_python_version: 3.7

app_packages:
  - git
  - python{{ flaskapp_python_version }}
  - build-essential
  - python-dev
  - python-pip
  - python-virtualenv
  - libpq-dev
  - build-essential
